### ISSUE TITLE
Potential instructions to install?

### ISSUE THREAD

**Issue by CodyGiles** [vyazadji/MMM-FullCalendar#1]
Hi @vyazadji I am creating a Dashboard using Magic Mirror running on my Raspberry Pi, and I wanted a full calendar on it. I stumbled across FullCalendar.io which eventually led me to this Repo.

I like the customization of Magic Mirror over Dakboard, but I am in way over my head and was wondering if you could help? How do I install FullCalendar and then this repo? I cloned this repo into my modules folder and that's about as far as I can get. Any help would be greatly appreciated! Thank you.

**Comment by vyazadji** [comment]
Hi @EvadingRye,

I've added an instruction in Readme. Let me know if you have any issues/questions.

**Comment by CodyGiles** [comment]
Wow, thank you @vyazadji - it all looks really clear to me. I'm unfortunately away from my Raspberry Pi until the weekend but I'm looking forward to trying it out. Thanks again for putting that together! I'll let you know how I do.

**Comment by CodyGiles** [comment]
Good news! I got everything working, the only hiccup I had was I didn't realize I needed to remove the '<' and '>' from the API part haha. My next project will be trying to get it so I don't have to have my Google Calendar public - I'm thinking that's going to be a bit of a challenge 🤔
